### ISSUE TITLE
"When you update your privacy policy, you inform existing customers Data Controller" doesn't seem to be in Article 7?

### ISSUE THREAD

**Issue by danielcompton** [privacyradius/gdpr-checklist#15]
There is a section that says

> When you update your privacy policy, you inform existing customers Data Controller
> for example, by emailing upcoming changes of your privacy policy. Your communication should explain in a simple way what has changed

With a link to https://advisera.com/eugdpracademy/gdpr/conditions-for-consent/. However reading Article 7, I couldn't see where it talked about changes to the privacy policy, and informing customers of updates to the policy. Is it in this section or another one?

**Comment by Gdewilde** [comment]
Thanks for your question, Daniel. @willem-delbare can you take this one?

**Comment by willem-delbare** [comment]
@danielcompton , you're correct. Article 7 is only loosely related and there is no GDPR article that explicitly states this guideline about privacy policies. The general idea is this: your customer might have consented to processing their data as described in your privacy policy at one point, but as you add new forms of processing (eg new features, integrations, subprocessors,...), that consent does not automatically extend to these new forms of processing.

Mostly, i referenced article 7 because it expresses an idea I really like, which is that consent is not binding if it's not in an intelligible and easily accessible form, using clear and plain language. The guideline I extracted from this is that you have to inform your customer proactively that you're doing something new, instead of the other way around.

Again, this is just our interpretation, and not legal advice.
